struct_field_align_threshold    = 10
format_code_in_doc_comments     = true
match_block_trailing_comma      = true
use_field_init_shorthand        = true
blank_lines_upper_bound         = 3
overflow_delimited_expr         = true
force_multiline_blocks          = true
combine_control_expr            = false
format_macro_bodies             = false
imports_granularity             = "Crate"
fn_single_line                  = true
format_strings                  = true
imports_layout                  = "HorizontalVertical"
wrap_comments                   = true
tab_spaces                      = 2